// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShedulerApp.Models;

#nullable disable

namespace ShedulerApp.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20221007111336_AccountStats")]
    partial class AccountStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ShedulerApp.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ShedulerApp.Models.AccountStats", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksExecuted")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("AccountStats");
                });

            modelBuilder.Entity("ShedulerApp.Models.UserInfo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastExecution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskParameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShedulerApp.Models.AccountStats", b =>
                {
                    b.HasOne("ShedulerApp.Models.Account", "Account")
                        .WithOne("AccountStat")
                        .HasForeignKey("ShedulerApp.Models.AccountStats", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ShedulerApp.Models.Account", b =>
                {
                    b.Navigation("AccountStat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
